services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq-test
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Frontend
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
